// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file audio.proto (package audio, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file audio.proto.
 */
export const file_audio: GenFile = /*@__PURE__*/
  fileDesc("CgthdWRpby5wcm90bxIFYXVkaW8iSQoLQXVkaW9QYWNrZXQSEwoLc2VxdWVuY2VfaWQYASABKA0SEgoKYXVkaW9fZGF0YRgCIAEoDBIRCgl0aW1lc3RhbXAYAyABKANiBnByb3RvMw");

/**
 * @generated from message audio.AudioPacket
 */
export type AudioPacket = Message<"audio.AudioPacket"> & {
  /**
   * @generated from field: uint32 sequence_id = 1;
   */
  sequenceId: number;

  /**
   * @generated from field: bytes audio_data = 2;
   */
  audioData: Uint8Array;

  /**
   * @generated from field: int64 timestamp = 3;
   */
  timestamp: bigint;
};

/**
 * Describes the message audio.AudioPacket.
 * Use `create(AudioPacketSchema)` to create a new message.
 */
export const AudioPacketSchema: GenMessage<AudioPacket> = /*@__PURE__*/
  messageDesc(file_audio, 0);

